### ISSUE TITLE
Hash bcrypt

### ISSUE THREAD

**Issue by kerbs-ns** [simonhamp/laravel-nova-csv-import#66]
Laravel as default uses bcrypt. it seems it is missing from modifiers hash_algos() is not present

**Comment by simonhamp** [comment]
`bcrypt` and other 'slow' hashing algorithms (e.g. argon2) aren't part of the [`hash_algos()`](https://www.php.net/manual/en/function.hash-algos.php) function output because they're part of the distinct [Password Hashing extension](https://www.php.net/manual/en/book.password.php)

See instead [`password_algos()`](https://www.php.net/manual/en/function.password-algos.php)

`bcrypt` is represented in the array from this function as `2y`:
![Screenshot 2023-06-14 at 12 47 38](https://github.com/simonhamp/laravel-nova-csv-import/assets/31628/92aba740-1eb9-4736-a4b6-e92e934b520d)
